### ISSUE TITLE
Update with v.9

### ISSUE THREAD

**Issue by sergy79** [aspnetboilerplate/eventcloud#10]
Hi, Can you please update with v 9, I am reading your site documentation and trying this as an exercise simultaneously. 

1. Can you add some comments in the sections where adding depts/orgs 
2. Also how to get users only inside that organization? For e.g. manager find all his employee/users to approve purchases.

thanks
Sergy

**Comment by hikalkan** [comment]
Have you seed the document: http://www.aspnetboilerplate.com/Pages/Documents/Zero/Organization-Units
