### ISSUE TITLE
unknown provider charactersfilterprovider

### ISSUE THREAD

**Issue by karen-hikesupport** [aspnetboilerplate/eventcloud#11]
Hi i am getting the issue like below while accessing page #/events

"unknown provider charactersfilterprovider" 
do you know how?

**Comment by hikalkan** [comment]
It's defined here: https://github.com/aspnetboilerplate/eventcloud/blob/6d352ac1674d592713919bb7ac7fb44f744b4e84/src/EventCloud.Web/App/Main/filters/truncate.js#L3

Maybe your browser cached something. Sure that you disabled caching.

**Comment by karen-hikesupport** [comment]
i have checked with clear cache, history and etc but still creating problem here, i think problem with injection dynamic service with angular controller. can u tell me or is there any document for that B'cse i have follow step exact like event cloud app, in spite of we got the error as above.

**Comment by karen-hikesupport** [comment]
ok I resolved now issue at my end with presentation
