### ISSUE TITLE
Can you please explain how multi-tenancy is achieved when using social logins in this?

### ISSUE THREAD

**Issue by kishoreinvits** [aspnetboilerplate/eventcloud#12]
I see that only one set of Social login keys are being configured.

If I have two different tenants say eventCloudCompany1 and eventCloudCompany2, how does this extend? Please throw some light if you had any thoughts in this lines.

Best, b

**Comment by hikalkan** [comment]
UserLogin (https://github.com/aspnetboilerplate/module-zero/blob/dev/src/Abp.Zero/Authorization/Users/UserLogin.cs#L11) has TenantId.
