### ISSUE TITLE
The info of the user is not saved on RegisterTenant

### ISSUE THREAD

**Issue by benrivero** [aspnetboilerplate/eventcloud#15]
Hi, first of all, I have learn more about ASP.NET Boilerplate and ASP.NET ZERO with this project and his post on codeproject. Great job!!!

I notice that using this project at the time to register a new Tenant (Using the "Become Tenant" form), this form ask for Name, Surname, Email and Password. All work's ok, only the Name and Surname is not saved, the app uses the constants for Name, Surname and UserName (admin). 

It's easy to fix (and extend as I do in my case), modifying the function CreateTenantAdminUser on the User entitie, passing this data to the function and populating accordingly the model. 

**Also is important to notice that you can´t use a UserName different to "admin" on the User entitie. :(**

**Comment by ismcagdas** [comment]
Hi @benrivero,

When a new tenant created, we are creating an admin user for that tenant.
We wanted to use admin username for first user in CreateTenantAdminUser method.

This is not a common rule but we implemented it that way.

I will check and fix the first problem, thanks for reporting this 😄

**Comment by benrivero** [comment]
@ismcagdas about the use of admin username for every admin user of the tenants, could be some way to override this? Or in a future version allow to change this?

Greetings

**Comment by ismcagdas** [comment]
Hi @benrivero,

We will keep admin username in AspNet Zero for our usage but you can change it in your project as you like.

You can simply modify CreateTenantAdminUser method of User class.

**Comment by benrivero** [comment]
Hi @ismcagdas , I already try that, but if I try to use any UserName different to admin, the app throws error, something like: "There is no entity User with id = X"

If I debug the process and query the database using "set transaction isolation level read uncommitted;" I can confirm that the User is created and the id that the error throws exist only that the transaction is not ended. 

If I use "admin" for UserName int that method CreateTenantAdminUser it works!!

**Comment by ismcagdas** [comment]
@benrivero, is this happening in AspNet Zero or eventcloud ?

**Comment by benrivero** [comment]
@ismcagdas I download a fresh ASP .NET Boilerplate project using the template: ASP .NET MVC 5.x and Angular, Entity Framework and module zero. 

I start from this project building my app but learning from the EventCloud project and copying some pieces of code and modifying accordingly to my needs. 

This is the relevant code: 

`var adminUser = Users.User.CreateTenantAdminUser(tenant.Id, model.EmailAddress, model.Password, model.Name, model.Surname); //here I pass two more parameters Name and Surname
                    
CheckErrors(await _userManager.CreateAsync(adminUser)); //Here i got the error (only if adminUser.UserName is different to "admin")
                    
await _unitOfWorkManager.Current.SaveChangesAsync(); //To get admin user's id`

**Comment by ismcagdas** [comment]
@benrivero please reopen if same error occurs with the latest ABP version.
