### ISSUE TITLE
Add two edition which have different features

### ISSUE THREAD

**Issue by hikalkan** [aspnetboilerplate/eventcloud#2]

**Comment by MisinformedDNA** [comment]
Would love to see this. It's not straightforward how to actually work with the module zero framework. More examples, like this, would be greatly appreciated.

**Comment by smartmeter** [comment]
I agree :+1:

**Comment by Ricky-G** [comment]
@hikalkan is it possible to see a sample where there are different features for different users.  I am specifically interested in seeing (even if its a sample) how to actually implement different dashboards and features for different users in a tenant

**Comment by ismcagdas** [comment]
@Ricky-G Features are Tenant based and cannot be customized per user. If you want to implement different dashboards for different users of same tenant, you can use Permissions.

**Comment by ismcagdas** [comment]
Moved to https://github.com/aspnetboilerplate/aspnetboilerplate/issues/4570
