### ISSUE TITLE
can't use style css file from index.html

### ISSUE THREAD

**Issue by JainAnkitAdelanteLabs** [aspnetboilerplate/eventcloud#25]
i want to use styles from index.html , but not able to use it in demo project

**Comment by maliming** [comment]
Can you explain more details?

**Comment by JainAnkitAdelanteLabs** [comment]
i am trying to use newstyle.css from index.html 
<link href="assets/css/newstyle.css" type="text/css">
for some custom changes, but this is not working ...

**Comment by maliming** [comment]
Try it here.
https://github.com/aspnetboilerplate/eventcloud/blob/master/aspnet-core-angular/angular/.angular-cli.json#L30

**Comment by JainAnkitAdelanteLabs** [comment]
but i want to use this from index because using from here it makes all css to inline ... and not able to get the line number of element style...

**Comment by JainAnkitAdelanteLabs** [comment]
yes i have but still not working

**Comment by maliming** [comment]
Can you share the project code to the github repository?

**Comment by JainAnkitAdelanteLabs** [comment]
it got resolved now ... after adding "/*" after assets in json file
