### ISSUE TITLE
How can I get the "service-proxies.ts" of Angular?

### ISSUE THREAD

**Issue by jakeuj** [aspnetboilerplate/eventcloud#28]
How to use dynamic web api layer feature of ABP?
I just found "AngularJS Integration" in the doc "[Building Dynamic Web API Controllers](https://aspnetboilerplate.com/Pages/Documents/Dynamic-Web-API)".
And I got 404 error at "http://localhost:21021/api/AbpServiceProxies/GetAll?type=angular".
How can I get the "service-proxies.ts" of Angular?

**Comment by maliming** [comment]
You can refer to this project: https://github.com/aspnetboilerplate/module-zero-core-template/tree/master/angular/nswag
