### ISSUE TITLE
Update-Database failed on SQL2014Express

### ISSUE THREAD

**Issue by wluijk** [aspnetboilerplate/eventcloud#30]
PM> Update-Database
**Both Entity Framework Core and Entity Framework 6 are installed. The Entity Framework Core tools are running. Use 'EntityFramework\Update-Database' for Entity Framework 6.**

> No DbContext was found in assembly 'EventCloud.Web.Host'. Ensure that you're using the correct assembly and that the type is neither abstract nor generic.

**Comment by acjh** [comment]
Select `EntityFrameworkCore` project...

**Comment by wluijk** [comment]
Works as a charm, thanks. The EventCloud.Web.Host doesnt start because of SqlServerRetryingExecutionStrategy. I will open new issue.

**Comment by ismcagdas** [comment]
@wluijk you can check https://github.com/aspnetboilerplate/aspnetboilerplate/issues/3221

**Comment by maliming** [comment]
Related #31
