### ISSUE TITLE
The configured execution strategy 'SqlServerRetryingExecutionStrategy' does not support user initiated transactions.

### ISSUE THREAD

**Issue by wluijk** [aspnetboilerplate/eventcloud#31]
The configured execution strategy 'SqlServerRetryingExecutionStrategy' does not support user initiated transactions. Use the execution strategy returned by 'DbContext.Database.CreateExecutionStrategy()' to execute all the operations in the transaction as a retriable unit.'

I tried: 

            builder.UseSqlServer(connection,
                options => {
                    options.EnableRetryOnFailure(
                        maxRetryCount: 10,
                        maxRetryDelay: TimeSpan.FromSeconds(30),
                        errorNumbersToAdd: null
                        );
                }
            );

in EventCloudDbContectConfigurer and updated the SQL database from 2014 to 2017 but both has no effect.

**Comment by maliming** [comment]
please see: https://github.com/aspnetboilerplate/aspnetboilerplate/issues/3221

**Comment by wluijk** [comment]
Is there no straight solution for this? Do i really need to go through all this stuff to have EventCloud as a multi tenant template for my project? Does it not simply run out of the box on SQL 2017? Do i miss configuring stuff?

**Comment by ismcagdas** [comment]
@wluijk I thought you are running the template on Azure. Are you running it locally ?
