### ISSUE TITLE
Question about ForeingKey EventID

### ISSUE THREAD

**Issue by amendez1000** [aspnetboilerplate/eventcloud#32]
Hello community, 

I have maybe a stupid question but I don't understand this code:

[ForeignKey("EventId")]
public virtual ICollection<EventRegistration> Registrations { get; protected set; }

I understand that there could be multi registrations for an event. But I don't understand the reason of these code: "[ForeignKey("EventId")]".

I would appreciate any comment on this. I have read the Boilerplate documentation and I don't see an explanation for this.

Thanks in advance.

Regards,
Arturo

**Comment by ismcagdas** [comment]
It refers to EventId field in EventRegistration entity, https://github.com/aspnetboilerplate/eventcloud/blob/master/mvc-angularjs/src/EventCloud.Core/Events/EventRegistration.cs#L19

**Comment by amendez1000** [comment]
> 
> 
> It refers to EventId field in EventRegistration entity, https://github.com/aspnetboilerplate/eventcloud/blob/master/mvc-angularjs/src/EventCloud.Core/Events/EventRegistration.cs#L19

**Comment by amendez1000** [comment]
I appraciate your help @ismcagdas. I will try my example.

**Comment by amendez1000** [comment]
I was doing something similar that is your example:

public class Question : Entity<Guid>, ICreationAudited
    {
        public const int MaxQuestionDescLength = 1000;

        [Required]
        [MaxLength(MaxQuestionDescLength)]
        public virtual string QuestionDesc { get; protected set; }

        public virtual bool Approved { get; protected set; }

        public long? CreatorUserId { get; set; }
        public DateTime CreationTime { get; set; }

        [ForeignKey("QuestionId")]
        public virtual ICollection<Answer> Answers { get; protected set; }

        [ForeignKey("QuestionId")]
        public virtual ICollection<QuestionAttachment> QuestionAttachments { get; protected set; }

At the end I have QuestionId. Answer and QuestionAttachment entities have the QuestionId foreing key and when I try to add the migration, I am getting this error:


There are multiple ForeignKeyAttributes which are pointing to same set of properties - '{'QuestionId'}' on entity type 'QuestionAttachment'.

If I delete the four lines:

        [ForeignKey("QuestionId")]
        public virtual ICollection<Answer> Answers { get; protected set; }

        [ForeignKey("QuestionId")]
        public virtual ICollection<QuestionAttachment> QuestionAttachments { get; protected set; }

I am not getting the error. I don't clear why in your example, EventId is foreing key in the Event entity.

I would appreciate any commet on this.

Thanks!

**Comment by acjh** [comment]
Can you show code for `Answer` and `QuestionAttachment`?

**Comment by amendez1000** [comment]
Yes, of course.

[Table("QuestionAttachment")]
    public class QuestionAttachment : Entity<long>, IAudited
    {
        public const int MaxQuestionAttachmentLength = 256;

        [Required]
        [ForeignKey("QuestionId")]
        public Question Question { get; set; }
        public Guid QuestionId { get; set; }


and

[Table("Answer")]
    public class Answer : Entity<long>, IAudited
    {
        public const int MaxAnswerDescLength = 1000;

        [Required]
        [MaxLength(MaxAnswerDescLength)]
        public virtual string AnswerDesc { get; protected set; }

        [ForeignKey(nameof(QuestionId))]
        public Question Question { get; protected set; }
        public Guid QuestionId { get; protected set; }

**Comment by acjh** [comment]
Try removing `ForeignKey` attributes:

```diff
- [ForeignKey("QuestionId")]
  public virtual ICollection<Answer> Answers { get; protected set; }

- [ForeignKey("QuestionId")]
  public virtual ICollection<QuestionAttachment> QuestionAttachments { get; protected set; }
```

**Comment by amendez1000** [comment]
Yes, at end I did it to keep moving. When I saw the event example project, I didn't understand why the code had something similar to this. But it is fine. Everything is ok now.

Thanks everybody.

**Comment by acjh** [comment]
I think the example is wrong.
