### ISSUE TITLE
Localize Error Messages in Entities

### ISSUE THREAD

**Issue by amendez1000** [aspnetboilerplate/eventcloud#33]
Hi everyone,

Does someone know we would add location in the service side (Entities)? For example in this line

https://github.com/aspnetboilerplate/eventcloud/blob/d5a8cbec0d2851763cf3519653ea77f5f8d383b4/mvc-angularjs/src/EventCloud.Core/Events/EventRegistration.cs#L64

I have read the Abp Location documentation, however, I don't have clear how I can do this. I am not sure how I can inject ILocalizationManager. I don't know where I need to do it.

I apologize if I am asking something very basic.

Thanks!!

Regards,
Arturo

**Comment by maliming** [comment]
For example: LoginFailed => Login failed!
You can localize using the L method in multiple locations.
please refer document: https://aspnetboilerplate.com/Pages/Documents/Localization

https://github.com/aspnetboilerplate/eventcloud/blob/1a3d7a491d802d7392b82f9698d46303c703a4b9/mvc-angularjs/src/EventCloud.Core/Localization/Source/EventCloud.xml#L30

https://github.com/aspnetboilerplate/eventcloud/blob/1a3d7a491d802d7392b82f9698d46303c703a4b9/mvc-angularjs/src/EventCloud.WebApi/Api/Controllers/AccountController.cs#L88

**Comment by amendez1000** [comment]
Hi,

When I try to do something similar in my Entity, L method is not found. In the default template for a .net core, in the UserRegistrationManager.cs, they use L, but I don't know understand why it works there and in my new Entity, it doesn't work.

private async Task<Tenant> GetActiveTenantAsync(int tenantId)
        {
            var tenant = await _tenantManager.FindByIdAsync(tenantId);
            if (tenant == null)
            {
                throw new UserFriendlyException(**L("UnknownTenantId{0}", tenantId**));
            }

            if (!tenant.IsActive)
            {
                throw new UserFriendlyException(L("TenantIdIsNotActive{0}", tenantId));
            }

            return tenant;
        }

My new Entity:

public static UserQuestion Create(string question)
        {
            if (string.IsNullOrEmpty(question))
            {
                throw new UserFriendlyException(L("NewTask"));
            }

L method is not found.

Do you know what I am missing?

Thanks!

**Comment by ismcagdas** [comment]
@amendez1000 don't do that in your entity, do it in your domain service or application service.

**Comment by amendez1000** [comment]
Ok, then the best practice is not add validations in your entities. Thanks!
