### ISSUE TITLE
Fail to compile EventCloud.Core

### ISSUE THREAD

**Issue by chlang** [aspnetboilerplate/eventcloud#6]
Hello Halil,

Thank you for sharing the work. I have clone the project and yet not able to compile. 
Below is the output from the build.

C:\Users\Chlang\Source\Repos\eventcloud\src\EventCloud.Core\Authorization\Roles\RoleStore.cs(17,15,17,19): error CS1729: 'AbpRoleStore<Tenant, Role, User>' does not contain a constructor that takes 4 arguments

C:\Users\Chlang\Source\Repos\eventcloud\src\EventCloud.Core\Users\UserStore.cs(20,15,20,19): error CS1729: 'AbpUserStore<Tenant, Role, User>' does not contain a constructor that takes 7 arguments

C:\Users\Chlang\Source\Repos\eventcloud\src\EventCloud.Core\Editions\EditionManager.cs(10,18,10,32): error CS7036: There is no argument given that corresponds to the required formal parameter 'editionRepository' of 'AbpEditionManager.AbpEditionManager(IRepository<Edition>, IRepository<EditionFeatureSetting, long>)'

C:\Users\Chlang\Source\Repos\eventcloud\src\EventCloud.Core\MultiTenancy\TenantManager.cs(11,15,11,19): error CS7036: There is no argument given that corresponds to the required formal parameter 'tenantFeatureRepository' of 'AbpTenantManager<Tenant, Role, User>.AbpTenantManager(IRepository<Tenant>, IRepository<TenantFeatureSetting, long>, AbpEditionManager)'

**Comment by hikalkan** [comment]
Hi,

Do you have still the problem? It should be compilable.

**Comment by chlang** [comment]
Hello, 
Yeah thank you for response, it is compilable now.
