### ISSUE TITLE
Missing email validation

### ISSUE THREAD

**Issue by GuilhermeMorais** [aspnetboilerplate/eventcloud#7]
I tried to create a new user, inserting "test" in every field, in e-mail I set "test@test" but I got one error without further information: "Form is not valid. Please check and fix errors."
  This is a error from the example or one error from the framework?

**Comment by hikalkan** [comment]
Hi,

test@test is not a valid email address.

**Comment by GuilhermeMorais** [comment]
Hi, Hikalkan,
   I know this is why I asked, I was aspecting a validation on e-mail input field, something like a validation message and so I didn't see any kind of "e-mail is invalid" message.

**Comment by hikalkan** [comment]
I know, just not implemented for this sample.

**Comment by GuilhermeMorais** [comment]
THANKS!

**Comment by patagoniahiker** [comment]
Hi when I tried this with .8 new relase and updated module zero update it breaks

**Comment by hikalkan** [comment]
@patagoniahiker what does not works? the eventcloud completely?

**Comment by patagoniahiker** [comment]
3 errors: Eventcloud with notification i.e. when I do nuget update module zero on event cloud with tenants

- Adding new tenant code throws an error.
- Sending notification (our new feature)
- User recipient - does not get the notification, I saw the sample code and pasted it from your help page.

**Comment by hikalkan** [comment]
OK, we will upgrade the solution to the latest version and test again.
Thanks.

**Comment by patagoniahiker** [comment]
awesome thanks, I will test too and let you know..

**Comment by ismcagdas** [comment]
Moved to https://github.com/aspnetboilerplate/aspnetboilerplate/issues/4569
