### ISSUE TITLE
Wrong parameter type cast using GetSettingValueAsync

### ISSUE THREAD

**Issue by jotamorais** [aspnetboilerplate/eventcloud#9]
I'm reading through the sample app and just found a weird thing. At https://github.com/aspnetboilerplate/eventcloud/blob/master/src/EventCloud.Core/Events/EventRegistrationPolicy.cs#L41 it's trying to cast `EventCloudSettingNames.MaxAllowedEventRegistrationCountInLast30DaysPerUser` (which is a `const string`) to `await SettingManager.GetSettingValueAsync<int>` (which is `int`) so, obviously it won't compile.

Can you please instruct the best way to get settings default value?

Thanks!

**Comment by hikalkan** [comment]
Hi,

Let's see the code:

    var maxAllowedEventRegistrationCountInLast30DaysPerUser = await SettingManager.GetSettingValueAsync<int>(EventCloudSettingNames.MaxAllowedEventRegistrationCountInLast30DaysPerUser);

It does not cast EventCloudSettingNames.MaxAllowedEventRegistrationCountInLast30DaysPerUser to integer. And it's compiled.

It gets a value from setting manager by it's name. And the name is defined as const string. So, this is the best way to get a setting.

**Comment by jotamorais** [comment]
Yep, you're completely right... it's my bad.
I forgot the `using Abp.Configuration;`

Thanks!

**Comment by hikalkan** [comment]
OK, you're welcome.
